<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cs_clear_images"
 *
 * Auto generated by Extension Builder 2016-04-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Clear Processed Images',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Angela Dudtkowski',
	'author_email' => 'dudtkowski@clickstorm.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);