<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cs_clear_images"
 *
 * Auto generated by Extension Builder 2016-04-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[clickstorm] Clear Processed Images',
	'description' => 'The extension adds a link to the clear cache menu (flush caches) for editors and admins, to delete the processed images and clear the frontend cache afterwards.',
	'category' => 'plugin',
	'author' => 'Angela Dudtkowski - clickstorm GmbH',
	'author_email' => 'dudtkowski@clickstorm.de',
    'author_company' => 'clickstorm GmbH',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);